from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from bee.core.run import Run
from bee.evidence.finding import Severity


def generate_model_card(
    run: Run,
    existing_card: dict | None = None,
) -> str:
    """Generate a BEE-compliant model card (README.md) from scan results.

    Returns a string suitable for writing to README.md.
    """
    r = run

    # Build YAML front-matter
    metadata = _build_metadata(r, existing_card or {})

    # Build the security section
    security_section = _build_security_section(r)

    # Build dependencies section
    deps_section = _build_dependencies_section(r)

    timestamp = datetime.fromtimestamp(r.timestamp).strftime("%Y-%m-%d")

    return (
        "---\n"
        f"{metadata}\n"
        "---\n\n"
        "# Model Card - BEE Security Report\n\n"
        f"**Generated by BEE Security Scanner on {timestamp}**\n\n"
        "## Security Assessment\n\n"
        f"{security_section}\n"
        f"{deps_section}"
    )


def _build_metadata(run: Run, existing: dict) -> str:
    """Build YAML front-matter metadata from scan results."""
    lines = []

    # Existing metadata takes precedence for known fields
    for key in ("model_name", "license", "tags", "pipeline_tag", "language"):
        val = existing.get(key)
        if val:
            if isinstance(val, list):
                lines.append(f"{key}:\n  - " + "\n  - ".join(str(v) for v in val))
            else:
                lines.append(f"{key}: {val}")

    # Add BEE-specific metadata
    lines.append("beescan:")
    lines.append(f"  version: {run.version}")
    lines.append(f"  target: {run.target}")
    lines.append(f"  timestamp: {datetime.fromtimestamp(run.timestamp).isoformat()}")

    # Decision
    lines.append(f"  decision: {run.decision}")

    # Severity counts
    lines.append(f"  findings:")
    lines.append(f"    total: {len(run.findings)}")
    lines.append(f"    critical: {run.severity_count(Severity.CRITICAL)}")
    lines.append(f"    high: {run.severity_count(Severity.HIGH)}")
    lines.append(f"    medium: {run.severity_count(Severity.MEDIUM)}")
    lines.append(f"    low: {run.severity_count(Severity.LOW)}")
    lines.append(f"    info: {run.severity_count(Severity.INFO)}")

    # Tags
    tags = existing.get("tags", [])
    if isinstance(tags, list):
        if run.decision == "block":
            tags.append("bee:scan:blocked")
        elif run.decision == "review":
            tags.append("bee:scan:review")
        else:
            tags.append("bee:scan:cleared")
        tags.append("beescan")
    else:
        tags = ["beescan", f"bee:scan:{run.decision}"]
    lines.append(f"  tags: {tags}")

    return "\n".join(lines)


def _build_security_section(run: Run) -> str:
    """Build the security assessment section."""
    r = run

    decision_text = {
        "allow": "✅ **Cleared** — No blocking issues found.",
        "review": "⚠️ **Review Recommended** — Some findings need attention.",
        "block": "❌ **Blocked** — Blocking issues detected.",
    }.get(r.decision, "❓ Decision unknown")

    # Summary stats
    summary = (
        f"| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Decision | {decision_text.strip()} |\n"
        f"| Total Findings | {len(r.findings)} |\n"
        f"| Critical | {r.severity_count(Severity.CRITICAL)} |\n"
        f"| High | {r.severity_count(Severity.HIGH)} |\n"
        f"| Medium | {r.severity_count(Severity.MEDIUM)} |\n"
        f"| Low | {r.severity_count(Severity.LOW)} |\n"
        f"| Info | {r.severity_count(Severity.INFO)} |\n"
    )

    # Provenance
    provenance = ""
    if r.provenance:
        p = r.provenance
        source = p.source
        artifact = p.artifact
        provenance = (
            "\n"
            "## Provenance\n\n"
            f"| Field | Value |\n"
            f"|-------|-------|\n"
            f"| Provider | {source.provider} |\n"
            f"| Repository | {source.repository or 'N/A'} |\n"
            f"| Revision | {source.revision or 'N/A'} |\n"
            f"| SHA-256 | `{artifact.sha256[:64] if artifact.sha256 else 'N/A'}` |\n"
            f"| Size | {artifact.size:,} bytes |\n"
        )

    # Vulnerabilities
    vulns = ""
    if r.vulnerabilities:
        vuln_rows = (
            "| Package | CVE | Severity | Description |\n"
            "|---------|-----|----------|-------------|\n"
        )
        for v in r.vulnerabilities:
            vuln_rows += (
                f"| {v.get('package', '?')} | {v.get('id', '?')} "
                f"| {v.get('severity', '?')} | {v.get('description', '')} |\n"
            )
        vulns = f"\n## Vulnerabilities\n\n{vuln_rows}\n"

    # Detailed findings
    findings_section = ""
    if r.findings:
        findings_rows = (
            "| ID | Severity | Category | Description |\n"
            "|-------|----------|----------|-------------|\n"
        )
        for f in sorted(r.findings, key=lambda x: x.severity.value):
            desc = f.description[:100] if f.description else f.title
            findings_rows += (
                f"| {f.id} | {f.severity.value} | {f.category} | {desc} |\n"
            )
        findings_section = f"\n## Detailed Findings\n\n{findings_rows}\n"

    return (
        f"{decision_text.strip()}\n"
        "\n"
        "## Scan Summary\n\n"
        f"This model was scanned using BEE Security Scanner v{run.version}.\n\n"
        f"{summary}"
        f"{provenance}"
        f"{vulns}"
        f"{findings_section}"
    )


def _build_dependencies_section(run: Run) -> str:
    """Build the dependencies section."""
    if not run.dependencies:
        return ""

    dep_rows = (
        "| Package | Version | Source |\n"
        "|---------|---------|--------|\n"
    )
    for d in run.dependencies:
        dep_rows += (
            f"| {d.get('package', '?')} | {d.get('version', '?')} | {d.get('path', '?')} |\n"
        )

    return f"\n## Dependencies\n\n{dep_rows}\n"


def save_model_card(
    run: Run,
    output_path: Path,
    existing_card: Path | None = None,
) -> Path:
    """Save the generated model card to a file."""
    existing = {}
    if existing_card and existing_card.is_file():
        try:
            content = existing_card.read_text()
            if content.startswith("---"):
                # Try to parse existing YAML front-matter
                import yaml

                parts = content.split("---", 2)
                if len(parts) >= 3:
                    try:
                        existing = yaml.safe_load(parts[1]) or {}
                    except yaml.YAMLError:
                        pass
        except OSError:
            pass

    card_text = generate_model_card(run, existing)
    output_path.write_text(card_text, encoding="utf-8")
    return output_path
